theme: jekyll-theme-cayman
# Site settings
title: jacky Blog
SEOTitle: jacky
header-img: img/post-bg-desk.jpg
email: bruse971@gmail.com
description: "Every failure is leading towards success."
keyword: "jacky"
url: "https://jackywxp.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "" # you code repository
